### ISSUE TITLE
role initialize_cluster.yml don't install the query service

### ISSUE THREAD

**Issue by pierreyvesv** [couchbaselabs/ansible-couchbase-server#14]
Hello,
after running couchbase playbook the query service setting, then the port 8093 is not open. I am using couchbase 7.0

`ansible-playbook -i inventory.yml ansible/playbook/couchbase/couchbase_install.yml`

After checking all the tab ,the couchbase_cluster task didn't show the query service.

The default_service are setuped as shown in full-vars.yml
```
couchbase_cluster:
  name: Demo
  protocol: http
  port: 8091
  notifications: true
  index_storage: default
  default_services:
    - data
    - index
    - query
```
the UI Settings tab don't show that the query service is enable.

If I go to the admin interface on the "query" tab a message is displayed:
"The query interface is only available on Couchbase clusters running the query service. No query nodes were found on this cluster."

on the master node , lsof don't show the port 8093 open.

```
sudo lsof -i -P -n | grep LISTEN | grep couch
beam.smp   7840       couchbase   17u  IPv4  45233      0t0  TCP *:21200 (LISTEN)
beam.smp   7840       couchbase   18u  IPv6  45235      0t0  TCP *:21200 (LISTEN)
epmd       7871       couchbase    3u  IPv4  44324      0t0  TCP *:4369 (LISTEN)
epmd       7871       couchbase    4u  IPv6  44325      0t0  TCP *:4369 (LISTEN)
beam.smp   7991       couchbase   33u  IPv4  48702      0t0  TCP *:21100 (LISTEN)
beam.smp   7991       couchbase   35u  IPv6  48705      0t0  TCP *:21100 (LISTEN)
beam.smp   7991       couchbase   49u  IPv4  48669      0t0  TCP *:8091 (LISTEN)
goxdcr     8160       couchbase    9u  IPv4  45681      0t0  TCP 127.0.0.1:9998 (LISTEN)
memcached  8169       couchbase    9u  IPv4  44631      0t0  TCP 127.0.0.1:11280 (LISTEN)
memcached  8169       couchbase   12u  IPv4  44638      0t0  TCP *:11210 (LISTEN)
memcached  8169       couchbase   13u  IPv6  44639      0t0  TCP *:11210 (LISTEN)
memcached  8169       couchbase   14u  IPv4  44642      0t0  TCP *:11209 (LISTEN)
memcached  8169       couchbase   15u  IPv6  44643      0t0  TCP *:11209 (LISTEN)
beam.smp   8706       couchbase   17u  IPv4  48614      0t0  TCP *:21300 (LISTEN)
beam.smp   8706       couchbase   18u  IPv6  48616      0t0  TCP *:21300 (LISTEN)
beam.smp   8706       couchbase   28u  IPv4  48645      0t0  TCP *:8092 (LISTEN)
prometheu  8750       couchbase    8u  IPv4  48666      0t0  TCP 127.0.0.1:9123 (LISTEN)
projector  9507       couchbase   10u  IPv4  53113      0t0  TCP *:9999 (LISTEN)
````

subsequent ansible task ansible-couchbase-server/tasks/configure/indexes.yml  will fail to connect to port 8093

Rerunning the playbook shows only a check on the service 'data' , 'index' and 'query' are missing
``` 
TASK [github_couchbase : Initialize the Cluster] 
**************************************************************
skipping: [coc002s-05] => (item={'hostname': 'coc001s-05', 'services': ['data']}) 
skipping: [coc002s-05] => (item={'hostname': 'coc002s-05', 'services': ['data']}) 
skipping: [coc002s-05] => (item={'hostname': 'coc003s-05', 'services': ['data']}) 
skipping: [coc003s-05] => (item={'hostname': 'coc001s-05', 'services': ['data']}) 
skipping: [coc003s-05] => (item={'hostname': 'coc002s-05', 'services': ['data']}) 
skipping: [coc003s-05] => (item={'hostname': 'coc003s-05', 'services': ['data']}) 
changed: [coc001s-05] => (item={'hostname': 'coc001s-05', 'services': ['data']})
skipping: [coc001s-05] => (item={'hostname': 'coc002s-05', 'services': ['data']}) 
skipping: [coc001s-05] => (item={'hostname': 'coc003s-05', 'services': ['data']}) 
```

**Comment by pierreyvesv** [comment]
I have found my issue : the solution is obvious: services have to be defined in couchbase_cluster and in each couchbase_nodes
```
couchbase_cluster:
...
  default_services:
    - data
    - index
    - query
```
and in the node
```
couchbase_nodes:
  - hostname: server1
    services:
      - data
      - index
      - query
  - hostname: server2
    services:
      - data
      - index
      - query
  - hostname: server3
    services:
      - data
      - index
      - query
```
