### ISSUE TITLE
Setting version to "community" doesn't really install community version

### ISSUE THREAD

**Issue by evgenyidf** [couchbaselabs/ansible-couchbase-server#20]
It keeps on trying to install the "enterprise" version.. even if you set :
```
couchbase_server_edition: 'community'
``` 
__I tried with the _7.0.0_ version__

If you try to overcome this by changing the: `tasks/install/redhat.yml` with following:
```
- name: Set the Couchbase Package Version with edition type
  set_fact:
    couchbase_server_version: "community-{{ couchbase_server_version }}"
  when:
    - couchbase_server_edition == 'community'
    - (couchbase_server_download_url is defined) and (couchbase_server_download_url | length == 0)
  tags:
    - couchbase_install
    
 - name: Install Couchbase Server package
  yum:
    name: "couchbase-server-{{ couchbase_server_version }}"

```
It fails on other, non-community version actions like:
- `tasks/configure/audit.yml`
- `tasks/configure/rebalance_settings.yml`
- `tasks/configure/security_settings.yml`
- `tasks/configure/server_groups.yml`

(*) I also have an issue with initial rebalancing, but this might be not related to license type...
