### ISSUE TITLE
When eviction_policy is set for a bucket play will always fail

### ISSUE THREAD

**Issue by ivan-nsure** [couchbaselabs/ansible-couchbase-server#21]
Hi,
When I set an eviction policy for a bucket inside the couchbase_buckets variable, the play will always fail.

Example configuration:

``` yaml
couchbase_buckets:
    - name: raw_data
      type: couchbase
      ram_size: 6500
      replicas: 1
      compression_mode: active
      eviction_policy: fullEviction
      conflict_resolution: sequence
```

The error message that I get:
`The buckets[*] 'conflict_resolution' property must be: sequence or timestamp`

This is because in the preflight tasks the validation is wrong.
https://github.com/couchbaselabs/ansible-couchbase-server/blob/dc0f1db2e5f8d7753fae94e15dd10ca030ae8acf/tasks/preflight/buckets.yml#L59

Should be changed to
``` yaml
when: ( item.eviction_policy is defined and item.conflict_resolution not in ['sequence', 'timestamp'] )
```

Same issue with next task
https://github.com/couchbaselabs/ansible-couchbase-server/blob/dc0f1db2e5f8d7753fae94e15dd10ca030ae8acf/tasks/preflight/buckets.yml#L68

Should be changed to
``` yaml
when: ( item.eviction_policy is defined and item.compression_mode not in ['off', 'passive', 'active'] )
```
